# coding=gbk
from typing import List

from jsonpath import jsonpath

data = {"Code": 200,
        "Data":
            {"Count": 6513,
             "Posts":
                 [
                     {"Id": 0,
                      "PostId": "1316417048615591936",
                      "RecruitPostId": 67237,
                      "RecruitPostName": "35948-腾讯云数据安全产品前端开发（深圳）",
                      "CountryName": "中国",
                      "LocationName": "深圳",
                      "BGName": "CSIG",
                      "ProductName": "",
                      "CategoryName": "技术",
                      "Responsibility": "- 负责PC端和移动端项目开发和维护；\n- 负责解决产品在不同浏览器、不同终端下的兼容问题；\n- 参与产品前端架构改进，提升团队开发效率。",
                      "LastUpdateTime": "2020年10月27日",
                      "PostURL": "http://careers.tencent.com/jobdesc.html?postId=1316417048615591936",
                      "SourceID": 1,
                      "IsCollect": "false",
                      "IsValid": "true"},
                     {"Id": 0, "PostId": "1316417049110519808", "RecruitPostId": 67238,
                      "RecruitPostName": "35948-腾讯云数据安全产品前端开发（北京）",
                      "CountryName": "中国", "LocationName": "北京", "BGName": "CSIG", "ProductName": "",
                      "CategoryName": "技术",
                      "Responsibility": "- 负责PC端和移动端项目开发和维护；\n- 负责解决产品在不同浏览器、不同终端下的兼容问题；\n- 参与产品前端架构改进，提升团队开发效率。",
                      "LastUpdateTime": "2020年10月27日",
                      "PostURL": "http://careers.tencent.com/jobdesc.html?postId=1316417049110519808",
                      "SourceID": 1, "IsCollect": "false", "IsValid": "true"},
                     {"Id": 0,
                      "PostId": "1206737489629286400",
                      "RecruitPostId": 55967,
                      "RecruitPostName": "21309-腾讯教育子公司-IMWeb团队web开发工程师（深圳））",
                      "CountryName": "中国",
                      "LocationName": "深圳",
                      "BGName": "CSIG",
                      "ProductName": "",
                      "CategoryName": "技术",
                      "Responsibility": "负责在线教育产品的内部管理系统和运营活动开发。",
                      "LastUpdateTime": "2020年10月27日",
                      "PostURL": "http://careers.tencent.com/jobdesc.html?postId=1206737489629286400",
                      "SourceID": 1,
                      "IsCollect": "false",
                      "IsValid": "true"},
                     {"Id": 0,
                      "PostId": "1277947140328398848",
                      "RecruitPostId": 63442,
                      "RecruitPostName": "21309-教育子公司-腾讯课堂-腾讯课堂教育内容运营(深圳)",
                      "CountryName": "中国",
                      "LocationName": "深圳",
                      "BGName": "CSIG",
                      "ProductName": "腾讯课堂",
                      "CategoryName": "产品",
                      "Responsibility": "1、 参与腾讯课堂全新知识内容社区的打造与内容运营，对专区内容建设与数据指标负责\n2、 负责发掘知识领域的优质内容创作者，进行合作洽谈，作者引入，激励沟通以及长期运营维护，深入了解创作者需求，并制定相应的产品策略\n3、 参与制定内容编辑/审核标准，根据用户需求对内容进行包装与优化，增强内容的观赏性，并根据内容数据反馈，持续调整内容方向与包装策略\n4、 参与管理内容编辑/审核团队，进行有效人力分工，对团队整体产出负责",
                      "LastUpdateTime": "2020年10月27日",
                      "PostURL": "http://careers.tencent.com/jobdesc.html?postId=1277947140328398848",
                      "SourceID": 1,
                      "IsCollect": "false",
                      "IsValid": "true"},
                     {"Id": 0,
                      "PostId": "1288673010575745024",
                      "RecruitPostId": 64487,
                      "RecruitPostName": "21309-教育子公司-系统测试工程师（深圳）",
                      "CountryName": "中国",
                      "LocationName": "深圳",
                      "BGName": "CSIG",
                      "ProductName": "",
                      "CategoryName": "技术",
                      "Responsibility": "岗位职责：\n1、负责CSIG在线教育业务腾讯课堂、企鹅辅导、腾讯开心鼠等产品的质量保障工作，包括测试用例评审，制定测试方案并评估风险、缺陷跟踪及质量分析等。\n2、负责业务的接口、UI等自动化测试的建设，提升产品的自动化能力；结合产品特征，挖掘产品相关的专项需求\n3、参与外包团队管理，带领外包同学完成需求及项目的交付，负责测试分析、自动化等能力的培训\n4、能独立负责产品的测试，包括但不限于功能、性能、稳定性、兼容性等方面，过程中保持和产品、开发、PM的高效沟通，快速推动问题的解决。\n",
                      "LastUpdateTime": "2020年10月27日",
                      "PostURL": "http://careers.tencent.com/jobdesc.html?postId=1288673010575745024",
                      "SourceID": 1,
                      "IsCollect": "false",
                      "IsValid": "true"},
                     {"Id": 0,
                      "PostId": "1268068627496574976",
                      "RecruitPostId": 62401,
                      "RecruitPostName": "WXG08-微信搜一搜服务搜索产品策划（广州）",
                      "CountryName": "中国",
                      "LocationName": "广州",
                      "BGName": "WXG",
                      "ProductName": "微信",
                      "CategoryName": "产品",
                      "Responsibility": "负责微信搜一搜中服务搜索的产品形态设计设计及用户体验提升；\n通过对用户需求的敏锐洞察和理解，结合细致的数据分析，策划创新的产品方案，最终加强用户对搜一搜服务搜索的认知理解并实现用户指标增长。",
                      "LastUpdateTime": "2020年10月27日",
                      "PostURL": "http://careers.tencent.com/jobdesc.html?postId=1268068627496574976",
                      "SourceID": 1,
                      "IsCollect": "false",
                      "IsValid": "true"},
                     {"Id": 0,
                      "PostId": "1230702486042447872",
                      "RecruitPostId": 57721,
                      "RecruitPostName": "28481-腾讯医疗高级前端开发工程师(深圳/北京)",
                      "CountryName": "中国",
                      "LocationName": "深圳",
                      "BGName": "CSIG",
                      "ProductName": "",
                      "CategoryName": "技术",
                      "Responsibility": "负责腾讯健康、电子医保凭证、电子健康卡等腾讯医疗在线服务的前端开发工作；\n负责腾讯医疗健康相关业务的前端架构与开发工作，设计与构建腾讯医疗的业务中台；\n参与国家各部位组织的国家级医疗基础设施的前端方案设计、建设与保障等工作。",
                      "LastUpdateTime": "2020年10月27日",
                      "PostURL": "http://careers.tencent.com/jobdesc.html?postId=1230702486042447872",
                      "SourceID": 1,
                      "IsCollect": "false",
                      "IsValid": "true"},
                     {"Id": 0,
                      "PostId": "1278893947963318272",
                      "RecruitPostId": 63571,
                      "RecruitPostName": "30625-腾讯广告游戏行业产品运营经理（深圳）",
                      "CountryName": "中国",
                      "LocationName": "深圳",
                      "BGName": "CDG",
                      "ProductName": "腾讯广告",
                      "CategoryName": "产品",
                      "Responsibility": "负责游戏行业广告主产品运营，深入了解行业发展趋势，洞察客户商业目标和需求；\n建设行业产品解决方案，达成客户商业诉求和目标；\n独立撰写商业数据分析报告，对行业产品方向、效果改进、运营决策等深层次问题进行挖掘并推进； \n撰写MRD，推进产品技术需求的落实及上线；\n总结头部客户赋能案例经验，总结行业打法，快速推进行业复制。\n\n",
                      "LastUpdateTime": "2020年10月27日",
                      "PostURL": "http://careers.tencent.com/jobdesc.html?postId=1278893947963318272",
                      "SourceID": 1,
                      "IsCollect": "false",
                      "IsValid": "true"},
                     {"Id": 0,
                      "PostId": "1278893952027598848",
                      "RecruitPostId": 63572,
                      "RecruitPostName": "30625-腾讯广告网服行业客户运营经理（深圳or北京）",
                      "CountryName": "中国",
                      "LocationName": "北京",
                      "BGName": "CDG",
                      "ProductName": "腾讯广告",
                      "CategoryName": "产品",
                      "Responsibility": "负责网服行业KA广告主客户运营，深入了解行业发展趋势，洞察客户商业目标和需求；\n建设行业产品解决方案，达成客户商业诉求和目标；\n独立撰写商业数据分析报告，对行业产品方向、效果改进、运营决策等深层次问题进行挖掘并推进； \n撰写MRD，推进产品技术需求的落实及上线；\n总结头部客户赋能案例经验，总结行业打法，快速推进行业复制。",
                      "LastUpdateTime": "2020年10月27日",
                      "PostURL": "http://careers.tencent.com/jobdesc.html?postId=1278893952027598848",
                      "SourceID": 1,
                      "IsCollect": "false",
                      "IsValid": "true"},
                     {"Id": 0,
                      "PostId": "1123175414701756416",
                      "RecruitPostId": 42953,
                      "RecruitPostName": "TEG02-网络管控系统后台开发工程师（深圳）",
                      "CountryName": "中国",
                      "LocationName": "深圳",
                      "BGName": "TEG",
                      "ProductName": "",
                      "CategoryName": "技术",
                      "Responsibility": "负责海量互联网服务基础架构监控系统、网络自动化管理工具研发；\n负责Linux下Java/GO/C++后台服务器端软件与运营平台研发；\n负责海量网络数据采集及大数据存储分析；",
                      "LastUpdateTime": "2020年10月27日",
                      "PostURL": "http://careers.tencent.com/jobdesc.html?postId=1123175414701756416",
                      "SourceID": 1,
                      "IsCollect": "false",
                      "IsValid": "true"}
                 ]
             }
        }

data2 = {
    "Code": 200,
    "Data":
        {
            "Count": 14,
            "Posts":
                [
                    {
                        "Id": 0,
                        "PostId": "1298864974013145088",
                        "RecruitPostId": 65468,
                        "RecruitPostName": "25927-移动游戏安全专项测试（成都）",
                        "CountryName": "中国",
                        "LocationName": "成都",
                        "BGName": "IEG",
                        "ProductName": "",
                        "CategoryName": "技术",
                        "Responsibility": "负责移动终端游戏的漏洞挖掘与测试分析；\r\n负责移动终端游戏上线前的漏洞测试，并提供修复建议；\r\n负责研发漏洞测试工具，提升测试效率。",
                        "LastUpdateTime": "2020年10月22日",
                        "PostURL": "http://careers.tencent.com/jobdesc.html?postId=1298864974013145088",
                        "SourceID": 1,
                        "IsCollect": "false",
                        "IsValid": "true"},
                    {
                        "Id": 0,
                        "PostId": "1318028218355163136",
                        "RecruitPostId": 67402,
                        "RecruitPostName": "22989-专有云POC高级测试工程师（成都/深圳）",
                        "CountryName": "中国",
                        "LocationName": "成都",
                        "BGName": "CSIG",
                        "ProductName": "腾讯云",
                        "CategoryName": "技术",
                        "Responsibility": "1、负责专有云方案的规划与设计，以解决业务痛点，并提供有竞争力的解决方案功能和技术特性；\n2、负责专有云全球POC测试方案设计和支撑，负责重大项目测试方案引导、准入测试、PK测试;\n3、基于客户需求和专有云解决方案架构，支撑业务方向的落地，并负责完成方案架构的集成验证和落地；\n4、参与专有云的需求分析、方案设计、产品和技术规划、方案架构设计。",
                        "LastUpdateTime": "2020年10月19日",
                        "PostURL": "http://careers.tencent.com/jobdesc.html?postId=0",
                        "SourceID": 1,
                        "IsCollect": "false",
                        "IsValid": "true"},
                    {
                        "Id": 0,
                        "PostId": "1316692552778260480",
                        "RecruitPostId": 67295,
                        "RecruitPostName": "CSIG17-AI系统高级测试工程师",
                        "CountryName": "中国",
                        "LocationName": "成都",
                        "BGName": "CSIG",
                        "ProductName": "",
                        "CategoryName": "技术",
                        "Responsibility": "负责腾讯云叮当语音助手相关ToB业务质量保障工作及叮当开放平台质量保障工作，腾讯云叮当开放平台对外输出腾讯在AI领域特别是人机对话场景中的各项领先技术，在各种行业方向上和多家优质企业进行了深度的合作，包括腾讯车联网，智能家居，智能音箱，智能穿戴，智能机器人，文旅等领域都有合作。具体工作内容如下：\n1、负责腾讯云叮当开放平台的质量保障及ToB业务定制需求的质量保障工作，负责全流程质量管控，包括参与需求分析，帮助完善需求与开发设计实现，合理设计测试计划，实施测试活动，跟进缺陷，协助研发分析定位问题；\n2、负责产品相关的测试方案，测试工具平台，自动化测试架构设计及实现工作；\n3、保证被测系统的质量，并通过测试流程和方法创新，提升研发的质量和效率\n4、担任测试架构师角色，推动产品代码可测性建设及产品架构可测试性拆解，应用并落地分层测试相关技术\n腾讯云叮当参考网址：dingdang.qq.com",
                        "LastUpdateTime": "2020年10月15日",
                        "PostURL": "http://careers.tencent.com/jobdesc.html?postId=0",
                        "SourceID": 1,
                        "IsCollect": "false",
                        "IsValid": "true"},
                    {
                        "Id": 0,
                        "PostId": "1316577457209352192",
                        "RecruitPostId": 67258,
                        "RecruitPostName": "22989-腾讯云数据库高级测试工程师",
                        "CountryName": "中国",
                        "LocationName": "成都",
                        "BGName": "CSIG",
                        "ProductName": "腾讯云",
                        "CategoryName": "技术",
                        "Responsibility": "负责腾讯云包括Mysql, PostgreSQL, Cynosdb等数据库产品的测试工作；\n负责分析产品需求，架构，设计测试方法和测试用例；\n负责产品功能，性能测试、竞品分析、稳定性，可靠性等专项测试工作\n负责建设产品相关的自动化测试以及必要的测试工具开发等工作；\n不断改进测试过程、方法和技术，提升产品质量。",
                        "LastUpdateTime": "2020年10月15日",
                        "PostURL": "http://careers.tencent.com/jobdesc.html?postId=0",
                        "SourceID": 1,
                        "IsCollect": "false",
                        "IsValid": "true"},
                    {
                        "Id": 0,
                        "PostId": "1245253770095366144",
                        "RecruitPostId": 59649,
                        "RecruitPostName": "WXG10-企业微信专项测试工程师（成都）",
                        "CountryName": "中国",
                        "LocationName": "成都",
                        "BGName": "WXG",
                        "ProductName": "企业微信",
                        "CategoryName": "技术",
                        "Responsibility": "负责企业微信产品测试； \n设计专项及系统测试方案，跟进项目测试过程，保证版本发布质量； \n协助团队提升测试效率与质量。",
                        "LastUpdateTime": "2020年10月15日",
                        "PostURL": "http://careers.tencent.com/jobdesc.html?postId=1245253770095366144", "SourceID": 1,
                        "IsCollect": "false",
                        "IsValid": "true"},
                    {
                        "Id": 0,
                        "PostId": "1314845647827902464",
                        "RecruitPostId": 67011,
                        "RecruitPostName": "CSIG17-云测试高级工程师（成都）",
                        "CountryName": "中国",
                        "LocationName": "成都",
                        "BGName": "CSIG",
                        "ProductName": "",
                        "CategoryName": "技术",
                        "Responsibility": "负责腾讯云产品的测试工作，分析系统相关需求、设计、架构等，设计测试方法和测试用例；\n挖掘并跟进实施性能、稳定性、可靠性等专项测试，保障和提升产品质量；\n跟进建设云平台产品相关的自动化测试以及必要的测试工具开发，提升测试效率。",
                        "LastUpdateTime": "2020年10月10日", "PostURL": "http://careers.tencent.com/jobdesc.html?postId=0",
                        "SourceID": 1,
                        "IsCollect": "false",
                        "IsValid": "true"},
                    {
                        "Id": 0,
                        "PostId": "1244911055587512320",
                        "RecruitPostId": 59600,
                        "RecruitPostName": "WXG10-153 企业微信质量管理工程师（成都）",
                        "CountryName": "中国",
                        "LocationName": "成都",
                        "BGName": "WXG",
                        "ProductName": "企业微信",
                        "CategoryName": "技术",
                        "Responsibility": "负责企业微信运营及研发质量管理工作， 工作内容包括但不限于：\n1、跟进现网运营质量问题、专题优化、故障等，牵头分析总结，跟进改善措施落地并评估效果；\n2、理解业务架构及实现原理，结合质量数据，识别风险提前规避；\n3、项目管理，管理及推进项目迭代，建设流程规范及指标，保障项目的顺利推进，提前预估项目风险；\n4、建设流程规范的同时，落地相应的系统及工具，提高研发及运营流程的健壮性，降低人为风险、提高效率；\n5、建立运营及研发质量管理框架、项目管理框架；",
                        "LastUpdateTime": "2020年10月07日",
                        "PostURL": "http://careers.tencent.com/jobdesc.html?postId=1244911055587512320",
                        "SourceID": 1,
                        "IsCollect": "false",
                        "IsValid": "true"},
                    {
                        "Id": 0,
                        "PostId": "1310895169335205888",
                        "RecruitPostId": 66836,
                        "RecruitPostName": "CSIG17-大数据高级测试工程师",
                        "CountryName": "中国",
                        "LocationName": "成都",
                        "BGName": "CSIG",
                        "ProductName": "",
                        "CategoryName": "技术",
                        "Responsibility": "负责大数据hadoop，spark，ES, hive，flink，clickhouse以及数据湖等相关产品的测试工作；\n分析产品相关需求、设计、架构等，设计测试方法和测试用例；挖掘并跟进实施性能测试、竞品对比测试、稳定性等专项测试，保障和提升产品质量；\n跟进建设产品相关的自动化测试以及必要的测试工具开发，提升测试效率。",
                        "LastUpdateTime": "2020年09月29日",
                        "PostURL": "http://careers.tencent.com/jobdesc.html?postId=0",
                        "SourceID": 1,
                        "IsCollect": "false",
                        "IsValid": "true"},
                    {
                        "Id": 0,
                        "PostId": "1307215881297731584",
                        "RecruitPostId": 66381,
                        "RecruitPostName": "CSIG17-云数据库测试高级工程师",
                        "CountryName": "中国",
                        "LocationName": "成都",
                        "BGName": "CSIG",
                        "ProductName": "",
                        "CategoryName": "技术",
                        "Responsibility": "负责腾讯云包括Mysql, Redis, Cynosdb等数据库产品的测试工作；\n负责分析产品需求，架构，设计测试方法和测试用例；\n负责产品功能，性能测试、竞品分析、稳定性，可靠性等专项测试工作\n负责建设产品相关的自动化测试以及必要的测试工具开发等工作；\n不断改进测试过程、方法和技术，提升产品质量。",
                        "LastUpdateTime": "2020年09月29日",
                        "PostURL": "http://careers.tencent.com/jobdesc.html?postId=1307215881297731584",
                        "SourceID": 1,
                        "IsCollect": "false",
                        "IsValid": "true"},
                    {
                        "Id": 0,
                        "PostId": "1154192479482810368",
                        "RecruitPostId": 52060,
                        "RecruitPostName": "CSIG17-腾讯云容器高级测试工程师",
                        "CountryName": "中国",
                        "LocationName": "成都",
                        "BGName": "CSIG",
                        "ProductName": "",
                        "CategoryName": "技术",
                        "Responsibility": "负责腾讯云公有云/私有云的容器/Kubernetes/Devops等产品的测试工作\n分析产品相关需求、设计、架构等，设计测试方法和测试用例；挖掘并跟进实施性能测试、竞品对比测试、稳定性等专项测试，保障和提升产品质量；\n跟进并建设产品相关的自动化测试以及必要的测试工具开发，提升测试效率。",
                        "LastUpdateTime": "2020年09月10日",
                        "PostURL": "http://careers.tencent.com/jobdesc.html?postId=1154192479482810368",
                        "SourceID": 1,
                        "IsCollect": "false",
                        "IsValid": "true"}
                ]
        }
}

data3 = {
    "code": 0,
    "msg": "成功",
    "data":
        {
            "role":
                {
                    "id": "1",
                    "roleName": "系统管理员",
                    "createUser": "",
                    "roleIevel": "1",
                    "remarks": "这是备注",
                    "isDefault": "1",
                    "createTime": "2020-12-16 19:28:59",
                    "isSelected": ["1", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "2", "20", "21",
                                   "22", "23", "24", "25", "26", "27", "28", "29", "3", "30", "31", "32", "33", "37",
                                   "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "5", "6", "7", "8", "9"],
                    "createUserName": "null"
                },
            "treeData": [
                {
                    "id": "1",
                    "permissionName": "系统管理",
                    "title": "系统管理",
                    "parentId": "-1",
                    "permissionFlag": "1",
                    "permissionUrl": "/api/users/mgr",
                    "permissionUrlByHttps": "null",
                    "route": "null",
                    "isMgr": 1,
                    "remarks": "系统管理",
                    "softNames": "null",
                    "children": [
                        {
                            "id": "2",
                            "permissionName": "用户管理",
                            "title": "用户管理",
                            "parentId": "1",
                            "permissionFlag": "1.1",
                            "permissionUrl": "/api/role/mgr",
                            "permissionUrlByHttps": "null",
                            "route": "null",
                            "isMgr": 1,
                            "remarks": "用户管理",
                            "softNames": "null",
                            "children": [
                                {
                                    "id": "26",
                                    "permissionName": "查询其他用户",
                                    "title": "查询其他用户",
                                    "parentId": "2",
                                    "permissionFlag": "1.1.1",
                                    "permissionUrl": "/account/queryGraphAccount",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                },
                                {
                                    "id": "27",
                                    "permissionName": "全局搜索用户",
                                    "title": "全局搜索用户",
                                    "parentId": "2",
                                    "permissionFlag": "1.1.2",
                                    "permissionUrl": "/account/queryAccount",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                },
                                {
                                    "id": "28",
                                    "permissionName": "删除用户",
                                    "title": "删除用户",
                                    "parentId": "2",
                                    "permissionFlag": "1.1.3",
                                    "permissionUrl": "/account/deleteAccount",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                },
                                {
                                    "id": "30",
                                    "permissionName": "添加用户",
                                    "title": "添加用户",
                                    "parentId": "2",
                                    "permissionFlag": "1.1.5",
                                    "permissionUrl": "/account/addAccount",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                },
                                {
                                    "id": "33",
                                    "permissionName": "管理员修改其他人密码",
                                    "title": "管理员修改其他人密码",
                                    "parentId": "2",
                                    "permissionFlag": "1.1.8",
                                    "permissionUrl": "/account/resetOtherPassword",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                }],
                            "install": "true",
                            "constraint": "null",
                            "isMenu": 0,
                            "roleId": "null"
                        },
                        {
                            "id": "3",
                            "permissionName": "用户组管理",
                            "title": "用户组管理",
                            "parentId": "1",
                            "permissionFlag": "1.2",
                            "permissionUrl": "/account",
                            "permissionUrlByHttps": "null",
                            "route": "null",
                            "isMgr": 1,
                            "remarks": "用户组管理",
                            "softNames": "null",
                            "children": [
                                {
                                    "id": "12",
                                    "permissionName": "分页用户组查询",
                                    "title": "分页用户组查询",
                                    "parentId": "3",
                                    "permissionFlag": "1.2.1",
                                    "permissionUrl": "/userGroup/queryUserGroup",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                },
                                {
                                    "id": "13",
                                    "permissionName": "用户组查询接口 ",
                                    "title": "用户组查询接口 ",
                                    "parentId": "3",
                                    "permissionFlag": "1.2.2",
                                    "permissionUrl": "/userGroup/queryUserGroupNotPage",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                },
                                {
                                    "id": "14",
                                    "permissionName": "通过ID查询用户组",
                                    "title": "通过ID查询用户组",
                                    "parentId": "3",
                                    "permissionFlag": "1.2.3",
                                    "permissionUrl": "/userGroup/queryUserGroupById",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                },
                                {
                                    "id": "15",
                                    "permissionName": "添加群组",
                                    "title": "添加群组",
                                    "parentId": "3",
                                    "permissionFlag": "1.2.4",
                                    "permissionUrl": "/userGroup/addUserGroup",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                },
                                {
                                    "id": "16",
                                    "permissionName": "修改群组",
                                    "title": "修改群组",
                                    "parentId": "3",
                                    "permissionFlag": "1.2.5",
                                    "permissionUrl": "/userGroup/updateUserGroup",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                },
                                {
                                    "id": "17",
                                    "permissionName": "删除用户组",
                                    "title": "删除用户组",
                                    "parentId": "3",
                                    "permissionFlag": "1.2.6",
                                    "permissionUrl": "/userGroup/deleteUserGroup",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                }],
                            "install": "true",
                            "constraint": "null",
                            "isMenu": 0,
                            "roleId": "null"
                        },
                        {
                            "id": "11",
                            "permissionName": "角色管理",
                            "title": "角色管理",
                            "parentId": "1",
                            "permissionFlag": "1.4",
                            "permissionUrl": "/role",
                            "permissionUrlByHttps": "null",
                            "route": "null",
                            "isMgr": 1,
                            "remarks": "null",
                            "softNames": "null",
                            "children": [
                                {
                                    "id": "18",
                                    "permissionName": "分页查询角色",
                                    "title": "分页查询角色",
                                    "parentId": "11",
                                    "permissionFlag": "1.4.1",
                                    "permissionUrl": "/role/queryRole",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                },
                                {
                                    "id": "19",
                                    "permissionName": "查询角色",
                                    "title": "查询角色",
                                    "parentId": "11",
                                    "permissionFlag": "1.4.2",
                                    "permissionUrl": "/role/queryRoleNotPage",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                },
                                {
                                    "id": "20",
                                    "permissionName": "查询角色拥有的资源",
                                    "title": "查询角色拥有的资源",
                                    "parentId": "11",
                                    "permissionFlag": "1.4.3",
                                    "permissionUrl": "/role/queryRolePermission",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                },
                                {
                                    "id": "21",
                                    "permissionName": "查询指定角色信息和资源信息",
                                    "title": "查询指定角色信息和资源信息",
                                    "parentId": "11",
                                    "permissionFlag": "1.4.4",
                                    "permissionUrl": "/role/queryRoleById",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                },
                                {
                                    "id": "22",
                                    "permissionName": "添加角色和权限",
                                    "title": "添加角色和权限",
                                    "parentId": "11",
                                    "permissionFlag": "1.4.5",
                                    "permissionUrl": "/role/addRole",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                },
                                {
                                    "id": "23",
                                    "permissionName": "修改角色和权限",
                                    "title": "修改角色和权限",
                                    "parentId": "11",
                                    "permissionFlag": "1.4.6",
                                    "permissionUrl": "/role/updateRole",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                },
                                {
                                    "id": "24",
                                    "permissionName": "删除角色",
                                    "title": "删除角色",
                                    "parentId": "11",
                                    "permissionFlag": "1.4.7",
                                    "permissionUrl": "/role/deleteRole",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                },
                                {
                                    "id": "25",
                                    "permissionName": "查看资源",
                                    "title": "查看资源",
                                    "parentId": "11",
                                    "permissionFlag": "1.4.8",
                                    "permissionUrl": "/role/menu",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                }],
                            "install": "true",
                            "constraint": "null",
                            "isMenu": 0,
                            "roleId": "null"
                        },
                        {
                            "id": "47",
                            "permissionName": "日志审计",
                            "title": "日志审计",
                            "parentId": "1",
                            "permissionFlag": "1.5",
                            "permissionUrl": "/user/queryLogger",
                            "permissionUrlByHttps": "null",
                            "route": "null",
                            "isMgr": 1,
                            "remarks": "日志审计",
                            "softNames": "null",
                            "children": [],
                            "install": "true",
                            "constraint": "null",
                            "isMenu": 0,
                            "roleId": "null"
                        },
                        {
                            "id": "29",
                            "permissionName": "用户信息",
                            "title": "用户信息",
                            "parentId": "1",
                            "permissionFlag": "1.6",
                            "permissionUrl": "/account/queryAccountById",
                            "permissionUrlByHttps": "null",
                            "route": "null",
                            "isMgr": 1,
                            "remarks": "null",
                            "softNames": "null",
                            "children": [
                                {
                                    "id": "31",
                                    "permissionName": "更新用户",
                                    "title": "更新用户",
                                    "parentId": "29",
                                    "permissionFlag": "1.6.1",
                                    "permissionUrl": "/account/updateAccount",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                },
                                {
                                    "id": "32",
                                    "permissionName": "忘记密码",
                                    "title": "忘记密码",
                                    "parentId": "29",
                                    "permissionFlag": "1.6.2",
                                    "permissionUrl": "/account/resetPassword",
                                    "permissionUrlByHttps": "null",
                                    "route": "null",
                                    "isMgr": 1,
                                    "remarks": "null",
                                    "softNames": "null",
                                    "children": [],
                                    "install": "true",
                                    "constraint": "null",
                                    "isMenu": 0,
                                    "roleId": "null"
                                }],
                            "install": "true",
                            "constraint": "null",
                            "isMenu": 0,
                            "roleId": "null"
                        }],
                    "install": "true",
                    "constraint": "null",
                    "isMenu": 0,
                    "roleId": "null"
                },
                {
                    "id": "46",
                    "permissionName": "流式计算",
                    "title": "流计算系统",
                    "parentId": "-1",
                    "permissionFlag": "10",
                    "permissionUrl": "http://sdc213.sefon.com:17061",
                    "permissionUrlByHttps": "",
                    "route": "/frame/sdc_snake",
                    "isMgr": 0,
                    "remarks": "null",
                    "softNames": "sdc_snake",
                    "children": [],
                    "install": "true",
                    "constraint": "null",
                    "isMenu": 1,
                    "roleId": "null"
                },
                {
                    "id": "39",
                    "permissionName": "管理平台",
                    "title": "大数据管理平台",
                    "parentId": "-1",
                    "permissionFlag": "2",
                    "permissionUrl": "null",
                    "permissionUrlByHttps": "null",
                    "route": "/",
                    "isMgr": 0,
                    "remarks": "null",
                    "softNames": "null",
                    "children": [],
                    "install": "true",
                    "constraint": "null",
                    "isMenu": 1,
                    "roleId": "null"
                },
                {
                    "id": "43",
                    "permissionName": "安装运维",
                    "title": "安装运维",
                    "parentId": "-1",
                    "permissionFlag": "3",
                    "permissionUrl": "null",
                    "permissionUrlByHttps": "null",
                    "route": "null",
                    "isMgr": 0,
                    "remarks": "null",
                    "softNames": "null",
                    "children": [
                        {
                            "id": "5",
                            "permissionName": "安装部署",
                            "title": "安装部署系统",
                            "parentId": "43",
                            "permissionFlag": "3.1",
                            "permissionUrl": "http://sdc213.sefon.com:18094/sdc_install/",
                            "permissionUrlByHttps": "null",
                            "route": "/frame/sdc_install",
                            "isMgr": 0,
                            "remarks": "null",
                            "softNames": "",
                            "children": [],
                            "install": "true",
                            "constraint": "null",
                            "isMenu": 1,
                            "roleId": "null"
                        },
                        {
                            "id": "6",
                            "permissionName": "运维监控",
                            "title": "运维监控系统",
                            "parentId": "43",
                            "permissionFlag": "3.2",
                            "permissionUrl": "http://sdc213.sefon.com:8080/index.html?key=admin&author=YWRtaW46YWRtaW4=",
                            "permissionUrlByHttps": "null",
                            "route": "/frame/sdp_monitor",
                            "isMgr": 0,
                            "remarks": "null",
                            "softNames": "ambari_server,sdc_console",
                            "children": [],
                            "install": "true",
                            "constraint": "null",
                            "isMenu": 1,
                            "roleId": "null"
                        },
                        {
                            "id": "41",
                            "permissionName": "命令解析",
                            "title": "命令解析系统",
                            "parentId": "43",
                            "permissionFlag": "3.3",
                            "permissionUrl": "",
                            "permissionUrlByHttps": "null",
                            "route": "/frame/sdc_shell",
                            "isMgr": 0,
                            "remarks": "null",
                            "softNames": "sdc_shell",
                            "children": [],
                            "install": "false",
                            "constraint": "null",
                            "isMenu": 1,
                            "roleId": "null"
                        },
                        {
                            "id": "42",
                            "permissionName": "日志分析",
                            "title": "日志分析系统",
                            "parentId": "43",
                            "permissionFlag": "3.4",
                            "permissionUrl": "http://sdc214.sefon.com:61888/index.html",
                            "permissionUrlByHttps": "null",
                            "route": "/frame/sdc_log",
                            "isMgr": 0,
                            "remarks": "",
                            "softNames": "sdc_log,sdc_replacesdclogpage,sdc_replacesdclogpage",
                            "children": [],
                            "install": "true",
                            "constraint": "",
                            "isMenu": 1,
                            "roleId": "null"
                        }],
                    "install": "true",
                    "constraint": "null",
                    "isMenu": 1,
                    "roleId": "null"
                },
                {
                    "id": "10",
                    "permissionName": "数据融合",
                    "title": "数据融合系统",
                    "parentId": "-1",
                    "permissionFlag": "4",
                    "permissionUrl": "http://sdc213.sefon.com:8355/ETLManager/",
                    "permissionUrlByHttps": "null",
                    "route": "/frame/sdc_etl",
                    "isMgr": 0,
                    "remarks": "null",
                    "softNames": "sdc_etl,sdc_etlmanager_designer,sdc_etlcluster",
                    "children": [],
                    "install": "false",
                    "constraint": "null",
                    "isMenu": 1,
                    "roleId": "null"
                },
                {
                    "id": "8",
                    "permissionName": "数据存储",
                    "title": "数据存储系统",
                    "parentId": "-1",
                    "permissionFlag": "5",
                    "permissionUrl": "http://sdc213.sefon.com:18083/ccm/",
                    "permissionUrlByHttps": "null",
                    "route": "/frame/sdc_storage",
                    "isMgr": 0,
                    "remarks": "null",
                    "softNames": "sdc_storage,sdc_mongodb,sdc_storage_monitor,sdc_ccm",
                    "children": [],
                    "install": "true",
                    "constraint": "null",
                    "isMenu": 1,
                    "roleId": "null"
                },
                {
                    "id": "44",
                    "permissionName": "数据仓库",
                    "title": "数据仓库系统",
                    "parentId": "-1",
                    "permissionFlag": "6",
                    "permissionUrl": "",
                    "permissionUrlByHttps": "",
                    "route": "",
                    "isMgr": 0,
                    "remarks": "null",
                    "softNames": "sdc_dw",
                    "children": [
                        {
                            "id": "45",
                            "permissionName": "仓库管理",
                            "title": "仓库管理系统",
                            "parentId": "44",
                            "permissionFlag": "6",
                            "permissionUrl": "http://sdc214.sefon.com:17001/",
                            "permissionUrlByHttps": "",
                            "route": "/frame/sdc_dw",
                            "isMgr": 0,
                            "remarks": "null",
                            "softNames": "sdc_dw",
                            "children": [],
                            "install": "true",
                            "constraint": "null",
                            "isMenu": 0,
                            "roleId": "null"
                        },
                        {
                            "id": "40",
                            "permissionName": "多维分析",
                            "title": "多维分析系统",
                            "parentId": "44",
                            "permissionFlag": "8",
                            "permissionUrl": "",
                            "permissionUrlByHttps": "",
                            "route": "/frame/sdc_sql",
                            "isMgr": 0,
                            "remarks": "null",
                            "softNames": "sdc_sql",
                            "children": [],
                            "install": "false",
                            "constraint": "null",
                            "isMenu": 0,
                            "roleId": "null"
                        }],
                    "install": "true",
                    "constraint": "null",
                    "isMenu": 1,
                    "roleId": "null"
                },
                {
                    "id": "9",
                    "permissionName": "数据检索",
                    "title": "数据检索系统",
                    "parentId": "-1",
                    "permissionFlag": "7",
                    "permissionUrl": "http://sdc214.sefon.com:18011/",
                    "permissionUrlByHttps": "null",
                    "route": "/frame/sdc_search",
                    "isMgr": 0,
                    "remarks": "null",
                    "softNames": "sdc_search",
                    "children": [],
                    "install": "true",
                    "constraint": "null",
                    "isMenu": 1,
                    "roleId": "null"
                },
                {
                    "id": "7",
                    "permissionName": "数据安全",
                    "title": "数据安全系统",
                    "parentId": "-1",
                    "permissionFlag": "9",
                    "permissionUrl": "",
                    "permissionUrlByHttps": "null",
                    "route": "/frame/sdc_security",
                    "isMgr": 0,
                    "remarks": "null",
                    "softNames": "sdc_security",
                    "children": [
                        {
                            "id": "37",
                            "permissionName": "数据安全",
                            "title": "管理员权限",
                            "parentId": "7",
                            "permissionFlag": "9.1",
                            "permissionUrl": "http://sdc214.sefon.com:6080/login.jsp?user=admin",
                            "permissionUrlByHttps": "null",
                            "route": "/frame/sdc_security",
                            "isMgr": 0,
                            "remarks": "null",
                            "softNames": "sdc_security",
                            "children": [],
                            "install": "true",
                            "constraint": "null",
                            "isMenu": 1,
                            "roleId": "null"
                        },
                        {
                            "id": "38",
                            "permissionName": "数据安全",
                            "title": "普通用户权限",
                            "parentId": "7",
                            "permissionFlag": "9.2",
                            "permissionUrl": "http://sdc214.sefon.com:6080/login.jsp?user=sf",
                            "permissionUrlByHttps": "null",
                            "route": "/frame/sdc_security",
                            "isMgr": 0,
                            "remarks": "null",
                            "softNames": "sdc_security",
                            "children": [],
                            "install": "true",
                            "constraint": "null",
                            "isMenu": 1,
                            "roleId": "null"
                        }],
                    "install": "false",
                    "constraint": "null",
                    "isMenu": 0,
                    "roleId": "null"
                }]
        }
}

permissionName: List = data3["data"]["treeData"]
for item in permissionName:

    print(item)

# result = jsonpath(data, "$.Data.Posts[:2]")
# result1 = jsonpath(data2, "$.Data.Posts[:2]")
# result1 = jsonpath(data2, "$..Posts[:2]")
# result1 = jsonpath(data2, "$..RecruitPostName")
result1 = jsonpath(data3, "$..permissionName")
print(result1)

for item in result1:
    print()
    print(item)
    print()
